# Generated by Django 4.1.4 on 2023-08-05 08:23

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objekty',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meno', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('fillcolor', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('diskusia', models.BigIntegerField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('nastavenia', models.JSONField(blank=True, null=True)),
                ('stupen_ochrany', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'objekty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Podskupiny',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meno', models.TextField(blank=True, null=True)),
                ('viditelnost', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('spravca', models.TextField(blank=True, null=True)),
                ('nastavenia', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'podskupiny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Skupiny',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meno', models.TextField(blank=True, null=True)),
                ('spravca', models.TextField(blank=True, null=True)),
                ('viditelnost', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, size=None)),
                ('nastavenia', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skupiny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Map_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupen2', models.BooleanField(default=True)),
                ('stupen3', models.BooleanField(default=True)),
                ('stupen4', models.BooleanField(default=True)),
                ('stupen5', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('map_settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.map_settings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
