# Generated by Django 4.1.4 on 2023-10-14 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='viditelnostmapa',
            table='test',
        ),
    ]
