# Generated by Django 4.1.4 on 2023-10-14 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_viditelnostmapa_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='fgh',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('globalne', models.TextField(blank=True, null=True)),
                ('prihlaseny', models.TextField(blank=True, null=True)),
                ('uzivatelia', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ViditelnostMapa',
        ),
    ]
