# Generated by Django 4.1.4 on 2023-10-14 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_fgh_delete_viditelnostmapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viditelnost_mapa',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('globalne', models.TextField(blank=True, null=True)),
                ('prihlaseny', models.TextField(blank=True, null=True)),
                ('uzivatelia', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='fgh',
        ),
    ]
