# Generated by Django 4.1.4 on 2023-10-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_viditelnost_mapa_delete_fgh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viditelnost_mapa',
            name='globalne',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viditelnost_mapa',
            name='prihlaseny',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='viditelnost_mapa',
            name='uzivatelia',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
