# Generated by Django 4.1.4 on 2023-11-14 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0006_alter_viditelnost_mapa_uzivatelia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprava', models.TextField(blank=True, default='')),
                ('level', models.BigIntegerField(default=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('videne', models.BooleanField(default=False)),
                ('odosielatel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odosielatel', to=settings.AUTH_USER_MODEL)),
                ('prijimatel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prijimatel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
