# Generated by Django 4.1.4 on 2023-11-14 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0007_notifikacie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifikacie',
            name='odosielatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odosielatel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notifikacie',
            name='prijimatel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prijimatel', to=settings.AUTH_USER_MODEL),
        ),
    ]
