# Generated by Django 4.1.4 on 2023-11-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0008_alter_notifikacie_odosielatel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='zdielanie_objektu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapis', models.BooleanField(default=False)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.objekty')),
                ('zdielane_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
