# Generated by Django 4.1.4 on 2023-12-28 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0009_zdielanie_objektu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diskusia',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonym_read', models.BooleanField(default=True)),
                ('anonym_write', models.BigIntegerField(default=0)),
                ('spravca', models.TextField(blank=True, null=True)),
                ('odbery', models.JSONField(blank=True, default=dict, null=True)),
                ('aktivna', models.BooleanField(default=True)),
                ('viditelnost', models.ForeignKey(blank=True, db_column='viditelnost', null=True, on_delete=django.db.models.deletion.CASCADE, to='map.viditelnost_mapa')),
            ],
        ),
        migrations.CreateModel(
            name='Diskusny_prispevok',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprava', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('karma', models.JSONField(blank=True, default=dict, null=True)),
                ('diskusia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='map.diskusia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
