# Generated by Django 4.1.4 on 2023-12-30 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_diskusia_viditelnost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
