# Generated by Django 4.1.4 on 2024-01-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_sprava'),
    ]

    operations = [
        migrations.DeleteModel(
            name='zdielanie_objektu',
        ),
    ]
