# Generated by Django 4.1.4 on 2024-01-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_diskusia_skupiny_aktivna_diskusia_skupiny_uzivatelia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskusia_skupiny',
            old_name='aktivna',
            new_name='pre_kazdeho',
        ),
        migrations.AddField(
            model_name='diskusia_skupiny',
            name='verejna',
            field=models.BooleanField(default=True),
        ),
    ]
