# Generated by Django 4.1.4 on 2024-01-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0019_rename_aktivna_diskusia_skupiny_pre_kazdeho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diskusny_prispevok_skupiny_komentar',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprava', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('karma', models.JSONField(blank=True, default=dict, null=True)),
                ('prispevok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.diskusny_prispevok_skupiny')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
