# Generated by Django 4.2.11 on 2024-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_diskusny_prispevok_skupiny_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_settings',
            name='legenda',
            field=models.BooleanField(default=True),
        ),
    ]
